# Generated by Django 3.2.4 on 2021-06-29 07:11

from django.db import migrations, models

import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAddModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=32)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=user.models.filepath
                    ),
                ),
            ],
        ),
    ]
